export const LANG_MAP = {
  'zh-Hans': 'zh-CN',
  'zh-Hant': 'zh-TW',
  'en': 'en-US',
  'ja': 'ja-JP',
  'ko': 'ko-KR',
  'th': 'th-TH',
  'vi': 'vi-VN',
  'id': 'id-ID',
  'ms': 'ms-MY',
  'es': 'es-ES',
  'fr': 'fr-FR',
  'de': 'de-DE',
  'pt': 'pt-BR',
  'ru': 'ru-RU',
  'it': 'it-IT',
  'tr': 'tr-TR',
  'ar': 'ar-SA'
}

export const FALLBACK_LANG = 'en-US'

export const SUPPORTED_LANGS = Object.keys(LANG_MAP)

export const localeOptions = [
  { code: 'zh-Hans', label: '简体中文', short: '简' },
  { code: 'zh-Hant', label: '繁體中文', short: '繁' },
  { code: 'en', label: 'English', short: 'EN' },
  { code: 'ja', label: '日本語', short: '日' },
  { code: 'ko', label: '한국어', short: '한' },
  { code: 'th', label: 'ภาษาไทย', short: 'TH' },
  { code: 'vi', label: 'Tiếng Việt', short: 'VI' },
  { code: 'id', label: 'Bahasa Indonesia', short: 'ID' },
  { code: 'ms', label: 'Bahasa Melayu', short: 'MS' },
  { code: 'es', label: 'Español', short: 'ES' },
  { code: 'fr', label: 'Français', short: 'FR' },
  { code: 'de', label: 'Deutsch', short: 'DE' },
  { code: 'pt', label: 'Português', short: 'PT' },
  { code: 'ru', label: 'Русский', short: 'RU' },
  { code: 'it', label: 'Italiano', short: 'IT' },
  { code: 'tr', label: 'Türkçe', short: 'TR' },
  { code: 'ar', label: 'العربية', short: 'AR' }
]

export function flatten(obj, prefix = '', result = {}) {
  for (const [key, value] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${key}` : key
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      flatten(value, fullKey, result)
      result[key] = result[key] || value
    } else {
      result[fullKey] = value
      result[key] = value
    }
  }
  return result
}

export const UNIAPP_OVERRIDES = {
  'en-US': {
    appTitle: 'Short Drama',
    all: 'All',
    forYou: 'For You',
    profile: 'Profile',
    episodeBrowse: 'Episode {num} of {total} · Browse',
    episodeTitle: 'Episode {num}',
    nowPlaying: 'Now playing',
    unlocked: 'Unlocked',
    creditCost: '{count} credits',
    premiumEpisode: 'Premium episode',
    unlockChapter: 'Unlock this chapter',
    unlockSubtitle: 'Use {count} credits to continue watching.',
    unlockWithCredits: 'Unlock with credits',
    signInCreate: 'Sign in / Create account',
    unlockedToast: 'Unlocked',
    loginEyebrow: 'Binge faster',
    loginTitle: 'Your Drama Pass',
    accountLabel: 'Username',
    passwordLabel: 'Password',
    nicknameLabel: 'Display name',
    captchaLabel: 'Verification code',
    requiredFields: 'Please enter username, password, and verification code',
    accountPlaceholder: 'Username',
    passwordPlaceholder: 'Password',
    captchaPlaceholder: 'Verification code',
    nicknamePlaceholder: 'Display name',
    registered: 'Account created. Please sign in',
    signedIn: 'Signed in',
    guest: 'Guest viewer',
    creditsAvailable: '{count} credits available',
    passwordInvalid: 'Password must be 8-64 chars with upper, lower, number, and special symbol',
    usernameInvalid: 'Username must be 5-32 chars, starting with a letter',
    dailyReward: 'Daily reward',
    myList: 'My list',
    watchHistory: 'Watch history',
    creditActivity: 'Credit activity',
    rewardAdded: 'Reward added',
    secondsWatched: '{count} seconds watched',
    durationText: '{count}',
    durationShort: '{count}s',
    chooseLanguage: 'Language',
    pleaseSignIn: 'Please sign in first',
    requestFailed: 'Request failed',
    rechargeCredits: 'Recharge credits',
    rechargeSuccess: 'Recharge completed',
    credits: 'credits',
    'category.aiDrama': 'AI Drama',
    'category.realDrama': 'Live Action',
    editProfile: 'Edit profile',
    orders: 'My orders',
    changePassword: 'Change password',
    notifications: 'Notifications',
    autoPlay: 'Auto play next',
    editNickname: 'Edit nickname',
    uploadAvatar: 'Upload avatar',
    oldPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    passwordMismatch: 'Passwords do not match',
    passwordUpdated: 'Password updated',
    profileUpdated: 'Profile updated',
    deleteConfirm: 'Are you sure?',
    clearHistory: 'Clear history',
    historyDeleted: 'Deleted',
    historyCleared: 'History cleared',
    favoriteRemoved: 'Removed from favorites',
    unlockDrama: 'Unlock full drama',
    unlockDramaConfirm: 'Unlock all episodes for {count} credits?',
    watchAd: 'Watch ad for reward',
    noOrders: 'No orders yet',
    orderNo: 'Order No.',
    orderStatus: 'Status',
    pending: 'Pending',
    paid: 'Paid',
    expired: 'Expired',
    refunded: 'Refunded',
    cancelled: 'Cancelled',
    closed: 'Closed',
    totalCredits: 'Total credits',
    consumeCredits: 'Consumed',
    settingsUpdated: 'Settings saved',
    accountSettings: 'Account',
    playbackSettings: 'Playback',
    announcements: 'Announcements',
    announcementList: 'Announcements',
    announcementEmpty: 'No announcements',
    announcementRead: 'Mark as read',
    announcementUnread: '{count} unread',
    vipMember: 'VIP Member',
    vipStatus: 'VIP Status',
    vipActive: 'Active',
    vipExpired: 'Expired',
    vipDaysLeft: '{count} days left',
    vipPackages: 'VIP Packages',
    feedback: 'Feedback',
    feedbackSubmit: 'Submit Feedback',
    feedbackList: 'My Feedback',
    feedbackType: 'Type',
    feedbackBug: 'Bug Report',
    feedbackSuggestion: 'Suggestion',
    feedbackConsultation: 'Consultation',
    feedbackComplaint: 'Complaint',
    feedbackOther: 'Other',
    feedbackTitle: 'Title',
    feedbackContent: 'Content',
    feedbackPlaceholder: 'Please describe your issue...',
    feedbackSubmitBtn: 'Submit',
    feedbackEmpty: 'No feedback submitted',
    feedbackStatusPending: 'Pending',
    feedbackStatusReplied: 'Replied',
    feedbackStatusResolved: 'Resolved',
    feedbackStatusClosed: 'Closed',
    feedbackReply: 'Admin Reply',
    feedbackDetail: 'Feedback Detail',
    vipDaily: 'Daily VIP',
    vipWeekly: 'Weekly VIP',
    vipMonthly: 'Monthly VIP',
    recharge: 'Credit Pack',
    durationDays: '{count} days',
    originalPrice: 'Original',
    buyNow: 'Buy Now',
    subscribe: 'Subscribe',
    systemAnnouncement: 'System',
    activityAnnouncement: 'Activity',
    views: 'views',
    records: 'My VIP Records',
    noPackages: 'No packages available',
    fillRequired: 'Please fill in all information',
    submitSuccess: 'Submitted successfully',
    adminLoginOnly: 'Admin accounts must use the web console',
    membershipTitle: 'Membership Center',
    membershipCurrentLevel: 'Current Level',
    membershipLevelNone: 'Free User',
    membershipLevelSilver: 'Silver',
    membershipLevelGold: 'Gold',
    membershipLevelDiamond: 'Diamond',
    membershipSpendProgress: 'Total Spent',
    membershipToNextLevel: 'Spend {amount} more to reach {level}',
    membershipPointMultiplier: 'Point Multiplier',
    membershipDailyFreeEpisodes: 'Daily Free Episodes',
    membershipEpisodeDiscount: 'Episode Discount',
    membershipDramaDiscount: 'Drama Discount',
    membershipAdFree: 'Ad-Free',
    membershipOfflineCache: 'Offline Cache',
    membershipPremiumSupport: 'Premium Support',
    membershipBirthdayGift: 'Birthday Gift',
    membershipBenefitsTitle: 'Level Benefits',
    membershipExchangeTitle: 'Exchange Points for VIP',
    membershipExchangeDays: 'Days',
    membershipExchangeBtn: 'Exchange',
    membershipExchangeConfirm: 'Spend {points} points for {days} days of {level}?',
    membershipExchangeSuccess: 'Exchange successful',
    membershipLevelSource: 'Level Source',
    membershipLevelSourceSpend: 'Total Spent',
    membershipLevelSourcePurchase: 'Package Purchase',
    membershipDailyFreeUsed: 'Used',
    membershipDailyFreeRemaining: 'Remaining',
    membershipDailyFreeResetAt: 'Reset at',
    membershipHistoryTitle: 'Level History',
    membershipNoHistory: 'No history',
    membershipBenefitDanmuStyle: 'Danmu Style',
    shopTitle: 'Points Shop',
    shopExchange: 'Exchange',
    shopExchangeConfirm: 'Spend {points} points for {name}?',
    shopVipPrice: 'VIP Price',
    shopStock: 'Stock',
    shopRecords: 'Records',
    shopPending: 'Pending',
    shopDelivered: 'Delivered',
    shopExchangeSuccess: 'Exchange successful',
    shopNoItems: 'No items',
    shopNoRecords: 'No records',
    shopItemOutOfStock: 'Out of stock',
    shopItemNotFound: 'Item not found',
    autoRenewalTitle: 'Auto Renewal',
    autoRenewalActive: 'Active',
    autoRenewalInactive: 'Inactive',
    autoRenewalSubscribe: 'Subscribe',
    autoRenewalCancel: 'Cancel',
    autoRenewalCancelSuccess: 'Cancelled',
    autoRenewalNextChargeAt: 'Next Charge',
    autoRenewalFailCount: 'Failures',
    vipLevelBadge: 'Badge',
    vipExchangeEntry: 'Exchange Points',
    rechargeFirstPurchaseBonus: 'First Purchase Bonus',
    rechargeWillUpgrade: 'Will Upgrade To',
    renewalDiscount: '{percent}% off',
    rechargePointsExpireHint: 'Some points expire',
    deleteSuccess: 'Deleted successfully',
    save: 'Save',
    saved: 'Saved',
    share: 'Share',
    like: 'Like',
    comment: 'Comment',
    likePending: 'Like API is not connected yet',
    commentPending: 'Comment API is not connected yet',
    homeTab: 'Home',
    theaterTab: 'Theater',
    storeTab: 'Store',
    mineTab: 'Mine',
    storeCenter: 'Store Center',
    search: 'Search',
    searchDrama: 'Search dramas',
    orderCreateFailed: 'Order creation failed',
    paymentLinkFailed: 'Payment link failed',
    paymentFailed: 'Payment failed',
    browse: 'Browse',
    details: 'Details',
    retry: 'Retry',
    videoLoadFailed: 'Video failed to load',
    downloadingVideo: 'Downloading video',
    play: 'Play',
    episodes: 'Episodes',
    recommend: 'Recommended',
    noSynopsis: 'No synopsis yet',
    selectPlan: 'Select plan',
    payMethod: 'Payment method',
    confirmRecharge: 'Confirm recharge',
    noTitles: 'No titles available',
    loading: 'Loading',
    passwordLabel: 'Password',
    oldPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    passwordMismatch: 'Passwords do not match',
    passwordUpdated: 'Password updated',
    profileUpdated: 'Profile updated',
    edit: 'Edit',
    cancel: 'Cancel',
    clear: 'Clear',
    delete: 'Delete',
    status: 'Status',
    actions: 'Actions',
    enabled: 'Enabled',
    disabled: 'Disabled',
    yes: 'Yes',
    noText: 'No',
    processing: 'Processing',
    confirm: 'Confirm',
    noData: 'No data',
    language: 'Language',
    settings: 'Settings',
    profile: 'Profile',
    myList: 'My List',
    watchHistory: 'Watch History',
    noWatchHistory: 'No watch history yet',
    announcementList: 'Announcements',
    willUpgrade: 'Will Upgrade',
    nicknamePlaceholder: 'Display name',
    autoRenewalActive: 'Active',
    autoRenewalInactive: 'Inactive',
    autoRenewalNextChargeAt: 'Next Charge',
    autoRenewalFailCount: 'Failures',
    autoRenewalSubscribe: 'Subscribe',
    autoRenewalCancel: 'Cancel',
    autoRenewalCancelSuccess: 'Cancelled',
    membershipLevelNone: 'Free User',
    membershipLevelSilver: 'Silver',
    membershipLevelGold: 'Gold',
    membershipLevelDiamond: 'Diamond',
    membershipLevelShortNone: 'N',
    membershipLevelShortSilver: 'S',
    membershipLevelShortGold: 'G',
    membershipLevelShortDiamond: 'D',
    autoRenewalSelectProduct: 'Select a plan',
    autoRenewalSubscribeConfirm: 'Subscribe to auto-renewal for {name}?'
  }
}

export const zhHansOverrides = {
  'zh-CN': {
    appTitle: '短剧',
    all: '全部',
    forYou: '推荐',
    profile: '我的',
    save: '追剧',
    saved: '已追',
    share: '分享',
    like: '点赞',
    comment: '评论',
    likePending: '点赞接口尚未接入，已预留入口',
    commentPending: '评论接口尚未接入，已预留入口',
    homeTab: '首页',
    theaterTab: '剧场',
    storeTab: '商城',
    mineTab: '我的',
    storeCenter: '商城中心',
    search: '搜索',
    searchDrama: '搜索短剧',
    orderCreateFailed: '订单创建失败',
    paymentLinkFailed: '支付链接获取失败',
    paymentFailed: '支付发起失败',
    browse: '浏览',
    details: '详情',
    retry: '重试',
    videoLoadFailed: '视频加载失败',
    downloadingVideo: '视频下载中',
    play: '播放',
    episodes: '剧集',
    recommend: '推荐',
    noSynopsis: '暂无简介',
    selectPlan: '选择套餐',
    payMethod: '支付方式',
    confirmRecharge: '确认充值',
    noTitles: '暂无短剧数据',
    episodeBrowse: '第 {num} 集（共 {total} 集）· 选集',
    episodeTitle: '第 {num} 集',
    nowPlaying: '播放中',
    unlocked: '可看',
    creditCost: '{count} 积分',
    premiumEpisode: '付费分集',
    unlockChapter: '解锁本集',
    unlockSubtitle: '消耗 {count} 积分后可继续观看。',
    unlockWithCredits: '积分解锁',
    signInCreate: '登录 / 注册',
    unlockedToast: '解锁成功',
    loading: '加载中',
    loginEyebrow: '精彩短剧',
    loginTitle: '短剧账号',
    accountLabel: '用户名',
    passwordLabel: '密码',
    nicknameLabel: '昵称',
    captchaLabel: '验证码',
    requiredFields: '请填写用户名、密码和验证码',
    accountPlaceholder: '用户名',
    passwordPlaceholder: '密码',
    captchaPlaceholder: '验证码',
    nicknamePlaceholder: '昵称',
    signIn: '登录',
    createAccount: '注册',
    registered: '注册成功，请登录',
    newAccount: '没有账号？去注册',
    existingAccount: '已有账号？去登录',
    signedIn: '登录成功',
    guest: '未登录',
    creditsAvailable: '可用积分：{count}',
    passwordInvalid: '密码需8-64位，包含大小写字母、数字和特殊符号',
    usernameInvalid: '用户名需5-32位，字母开头，仅含字母、数字和下划线',
    signOut: '退出',
    dailyReward: '每日签到',
    myList: '我的追剧',
    watchHistory: '观看历史',
    creditActivity: '积分记录',
    rewardAdded: '签到成功',
    secondsWatched: '已看到 {count} 秒',
    durationText: '{count}',
    durationShort: '{count}秒',
    language: '语言',
    chooseLanguage: '语言',
    pleaseSignIn: '请先登录',
    requestFailed: '请求失败',
    rechargeCredits: '积分充值',
    rechargeSuccess: '充值成功',
    credits: '积分',
    'category.aiDrama': 'AI 短剧',
    'category.realDrama': '真人短剧',
    editProfile: '编辑资料',
    settings: '设置',
    orders: '我的订单',
    changePassword: '修改密码',
    notifications: '消息通知',
    autoPlay: '自动连播',
    editNickname: '修改昵称',
    uploadAvatar: '上传头像',
    oldPassword: '当前密码',
    newPassword: '新密码',
    confirmPassword: '确认新密码',
    passwordMismatch: '两次密码不一致',
    passwordUpdated: '密码修改成功',
    profileUpdated: '资料已更新',
    delete: '删除',
    cancel: '取消',
    clear: '清空',
    deleteConfirm: '确定要删除吗？',
    clearHistory: '清空历史',
    historyDeleted: '已删除',
    historyCleared: '历史已清空',
    favoriteRemoved: '已取消收藏',
    unlockDrama: '解锁整部剧',
    unlockDramaConfirm: '确定消耗 {count} 积分解锁整部剧？',
    watchAd: '看广告得积分',
    noOrders: '暂无订单',
    orderNo: '订单号',
    orderStatus: '状态',
    pending: '待支付',
    paid: '已支付',
    expired: '已过期',
    refunded: '已退款',
    cancelled: '已取消',
    closed: '已关闭',
    totalCredits: '总积分',
    consumeCredits: '已消耗',
    settingsUpdated: '设置已保存',
    accountSettings: '账号设置',
    playbackSettings: '播放设置',
    announcements: '系统公告',
    announcementList: '系统公告',
    announcementEmpty: '暂无公告',
    announcementRead: '标记已读',
    announcementUnread: '{count} 条未读',
    vipMember: 'VIP会员',
    vipStatus: 'VIP状态',
    vipActive: '生效中',
    vipExpired: '已过期',
    vipDaysLeft: '剩余 {count} 天',
    vipPackages: '会员套餐',
    feedback: '用户反馈',
    feedbackSubmit: '提交反馈',
    feedbackList: '我的反馈',
    feedbackType: '反馈类型',
    feedbackBug: 'Bug反馈',
    feedbackSuggestion: '建议反馈',
    feedbackConsultation: '咨询反馈',
    feedbackComplaint: '投诉反馈',
    feedbackOther: '其他反馈',
    feedbackTitle: '标题',
    feedbackContent: '内容',
    feedbackPlaceholder: '请描述您的问题或建议...',
    feedbackSubmitBtn: '提交',
    feedbackEmpty: '暂无反馈记录',
    feedbackStatusPending: '待处理',
    feedbackStatusReplied: '已回复',
    feedbackStatusResolved: '已解决',
    feedbackStatusClosed: '已关闭',
    feedbackReply: '管理员回复',
    feedbackDetail: '反馈详情',
    vipDaily: '日卡会员',
    vipWeekly: '周卡会员',
    vipMonthly: '月卡会员',
    recharge: '积分充值',
    durationDays: '{count}天',
    originalPrice: '原价',
    buyNow: '立即购买',
    subscribe: '立即开通',
    systemAnnouncement: '系统公告',
    activityAnnouncement: '活动公告',
    views: '阅读',
    records: '我的VIP记录',
    noPackages: '暂无套餐',
    fillRequired: '请填写完整信息',
    submitSuccess: '提交成功',
    adminLoginOnly: '管理员账号请使用网页运营后台登录',
    membershipTitle: '会员中心',
    membershipCurrentLevel: '当前等级',
    membershipLevelNone: '普通用户',
    membershipLevelSilver: '银牌会员',
    membershipLevelGold: '金牌会员',
    membershipLevelDiamond: '钻石会员',
    membershipSpendProgress: '累计消费',
    membershipToNextLevel: '再消费 {amount} 即可升级至 {level}',
    membershipPointMultiplier: '积分加成',
    membershipDailyFreeEpisodes: '每日免费集数',
    membershipEpisodeDiscount: '单集折扣',
    membershipDramaDiscount: '整剧折扣',
    membershipAdFree: '去广告',
    membershipOfflineCache: '离线缓存',
    membershipPremiumSupport: '专属客服',
    membershipBirthdayGift: '生日礼包',
    membershipBenefitsTitle: '等级权益对比',
    membershipExchangeTitle: '积分兑换会员',
    membershipExchangeDays: '天',
    membershipExchangeBtn: '兑换',
    membershipExchangeConfirm: '确认消耗 {points} 积分兑换 {days} 天 {level}？',
    membershipExchangeSuccess: '兑换成功',
    membershipLevelSource: '等级来源',
    membershipLevelSourceSpend: '累计消费',
    membershipLevelSourcePurchase: '购买套餐',
    membershipDailyFreeUsed: '已用',
    membershipDailyFreeRemaining: '剩余',
    membershipDailyFreeResetAt: '重置时间',
    membershipHistoryTitle: '等级历史',
    membershipNoHistory: '暂无记录',
    membershipBenefitDanmuStyle: '弹幕样式',
    shopTitle: '积分商城',
    shopExchange: '兑换',
    shopExchangeConfirm: '确认消耗 {points} 积分兑换 {name}？',
    shopVipPrice: '会员价',
    shopStock: '库存',
    shopRecords: '兑换记录',
    shopPending: '待发货',
    shopDelivered: '已发货',
    shopExchangeSuccess: '兑换成功',
    shopNoItems: '暂无商品',
    shopNoRecords: '暂无记录',
    shopItemOutOfStock: '库存不足',
    shopItemNotFound: '商品不存在',
    autoRenewalTitle: '自动续费',
    autoRenewalActive: '已开通',
    autoRenewalInactive: '未开通',
    autoRenewalSubscribe: '开通自动续费',
    autoRenewalCancel: '取消自动续费',
    autoRenewalCancelSuccess: '已取消',
    autoRenewalNextChargeAt: '下次扣款',
    autoRenewalFailCount: '失败次数',
    vipLevelBadge: '等级徽章',
    vipExchangeEntry: '积分兑换会员',
    rechargeFirstPurchaseBonus: '首充奖励',
    rechargeWillUpgrade: '购买后将升级至',
    renewalDiscount: '{percent}折',
    rechargePointsExpireHint: '赚取积分12个月后过期，购买积分永久有效',
    deleteSuccess: '删除成功',
    edit: '编辑',
    status: '状态',
    enabled: '启用',
    disabled: '禁用',
    yes: '是',
    noText: '否',
    processing: '处理中',
    confirm: '确认',
    noData: '暂无数据',
    profile: '我的',
    myList: '我的追剧',
    watchHistory: '观看历史',
    noWatchHistory: '暂无观看历史',
    announcementList: '系统公告',
    willUpgrade: '购买后将升级至',
    nicknamePlaceholder: '昵称',
    autoRenewalActive: '已开通',
    autoRenewalInactive: '未开通',
    autoRenewalNextChargeAt: '下次扣款',
    autoRenewalFailCount: '失败次数',
    autoRenewalSubscribe: '开通自动续费',
    autoRenewalCancel: '取消自动续费',
    autoRenewalCancelSuccess: '已取消',
    membershipLevelNone: '普通用户',
    membershipLevelSilver: '银牌会员',
    membershipLevelGold: '金牌会员',
    membershipLevelDiamond: '钻石会员',
    membershipLevelShortNone: '普',
    membershipLevelShortSilver: '银',
    membershipLevelShortGold: '金',
    membershipLevelShortDiamond: '钻',
    autoRenewalSelectProduct: '选择套餐',
    autoRenewalSubscribeConfirm: '确认开通「{name}」的自动续费？'
  }
}
