// English (US) language pack
export default {
  brand: {
    name: 'Star Marastel',
    fullName: 'Star Marastel',
    kicker: 'Marastel · AI Drama Platform',
    companyEn: 'Star Marastel Co., Limited',
    companyEnName: 'Star Marastel Co., Limited',
    copyright: 'All rights reserved.',
    paymentNote: 'Secure payments handled by Stripe. Visa, Mastercard, American Express, Apple Pay & Google Pay supported.'
  },

  nav: {
    home: 'Home',
    pricing: 'Pricing',
    vip: 'VIP',
    credits: 'Credits',
    contact: 'Contact',
    startNow: 'Get Started',
    menuAria: 'Menu',
    closeAria: 'Close'
  },

  footer: {
    desc: 'An AI-powered drama streaming platform. All content generated by AI — unique art styles, fresh stories. VIP for unlimited streaming, credits to unlock single episodes.',
    platform: 'Platform',
    legal: 'Legal',
    company: 'Company',
    privacy: 'Privacy Policy',
    refund: 'Refund Policy',
    terms: 'Terms of Service'
  },

  home: {
    heroTitle1: 'Stories from AI.',
    heroTitle2: 'Endless Possibilities.',
    heroSubtitle: 'An AI-powered streaming platform featuring original short dramas. Every series is generated by our in-house models — unique art, fresh stories, updated daily. VIP for unlimited access, credits for single episodes. Stripe secure payment worldwide.',
    viewPlans: 'Start Watching',
    browseNow: 'Browse Catalog',
    stats: {
      works: 'AI Drama Works',
      countries: 'Countries Covered',
      audience: 'Global Viewers'
    },

    modelsKicker: 'How to Watch',
    modelsTitle: 'Two modes, your choice',
    modelsSubtitle: 'Flexible options to fit your viewing habits. Save more with a subscription, pay less per episode with credits.',

    vipBadge: 'VIP Membership',
    vipTitle: 'VIP Unlimited Access',
    vipDesc: 'Unlock the entire AI drama library — unlimited streaming, zero ads, no waiting. New AI-generated series every day across sci-fi, fantasy, cyberpunk and more.',
    vipFeatures: ['Full AI drama library, no limits', 'New AI-generated series daily', '4K HD & AI-enhanced quality', 'Cancel anytime, no commitment'],
    vipCta: 'View VIP Plans →',

    creditBadge: 'Credits',
    creditTitle: 'Pay per Episode with Credits',
    creditDesc: 'Buy credit packs to unlock individual AI drama episodes. Perfect for trying before you binge. Credits never expire.',
    creditFeatures: ['Unlock individual episodes', 'Credits never expire', 'Starting at $4.99', 'First episode always free'],
    creditCta: 'View Credit Packs →',

    featuredKicker: 'This Week\'s Trending AI Dramas',
    featuredTitle: 'Featured AI Dramas',
    featuredSubtitle: 'Click any card to see details and start your AI drama journey.',
    aiBadge: 'AI',
    episodes: (n) => `${n} eps`,

    whyKicker: 'Why Star Marastel',
    whyTitle: 'Built for AI drama lovers',

    scaleKicker: 'By the numbers',
    scaleTitle: 'The AI drama streaming platform',
    scaleSubtitle: 'Star Marastel focuses exclusively on AI-generated dramas. Our in-house StarNovel and StarBrush models deliver a unique content experience to viewers worldwide.',
    scaleItems: {
      dailyUpdate: 'Daily Updates',
      aiNewWorks: 'New AI Works',
      serviceUptime: 'Service Uptime'
    },

    ctaTitle: 'Ready to enter the world of AI dramas?',
    ctaSubtitle: 'Pick a plan that fits you and start your unique AI drama experience today.',
    viewPricing: 'See Pricing',

    modalEpisodes: (n) => `${n} eps`,
    modalRegion: (r) => r,
    aiStudioLabel: 'AI Studio',
    aiModelLabel: 'AI Model',
    watchNow: 'Watch Now',
    keepBrowsing: 'Keep Browsing',

    features: [
      {
        iconKey: 'aiExclusive',
        title: 'AI-Exclusive Content',
        description: 'Every drama generated by our in-house StarNovel + StarBrush AI models — unique art, original stories.'
      },
      {
        iconKey: 'speedUpdate',
        title: 'Lightning-fast Updates',
        description: 'AI production is faster. New AI-generated series every day, so there\'s always something fresh to watch.'
      },
      {
        iconKey: 'securePayment',
        title: 'Secure Payments',
        description: 'Stripe encrypted global payments. Visa, Mastercard, Apple Pay, Google Pay supported.'
      },
      {
        iconKey: 'creditsForever',
        title: 'Credits Never Expire',
        description: 'Purchased credits are permanent. Unlock anytime you want.'
      },
      {
        iconKey: 'support',
        title: '24/7 Customer Support',
        description: 'Round-the-clock online support. Reach out anytime — we respond fast.'
      },
      {
        iconKey: 'cancelAnytime',
        title: 'Cancel Anytime',
        description: 'VIP membership has no contracts and no cancellation fees. Cancel whenever you want.'
      }
    ],

    fallbackDramas: [
      { id: 'fb-1', title: 'Hidden Love', genre: 'Romance', episodes: 80, rating: 4.8, region: 'CN', description: 'Childhood sweethearts torn apart by family feud. Years later, a reunion changes everything.', gradient: 'linear-gradient(135deg, #C86D26, #6b3410)' },
      { id: 'fb-2', title: 'Midnight Contract', genre: 'Mystery', episodes: 60, rating: 4.6, region: 'KR', description: 'A mysterious contract pulls an ordinary girl into a vast conspiracy.', gradient: 'linear-gradient(135deg, #2d5a3d, #0f1f15)' },
      { id: 'fb-3', title: 'City Lights', genre: 'Urban', episodes: 100, rating: 4.7, region: 'CN', description: 'Three young dreamers chase their light among the concrete jungle of the big city.', gradient: 'linear-gradient(135deg, #4a3b6b, #1a1430)' },
      { id: 'fb-4', title: 'Sweet Revenge', genre: 'Comedy', episodes: 48, rating: 4.5, region: 'CN', description: 'After being betrayed, a woman transforms into an angel of revenge. A tearful urban comedy.', gradient: 'linear-gradient(135deg, #b5651d, #5c2f08)' },
      { id: 'fb-5', title: 'Your Echo', genre: 'Romance', episodes: 72, rating: 4.9, region: 'KR', description: 'A bond across time — two lonely souls connected through a walkie-talkie.', gradient: 'linear-gradient(135deg, #7d2e4a, #341220)' },
      { id: 'fb-6', title: 'The Heir', genre: 'Business', episodes: 90, rating: 4.7, region: 'CN', description: 'One night transforms a nobody into a billionaire heir. Every step must be calculated.', gradient: 'linear-gradient(135deg, #1a4a5c, #08222b)' }
    ]
  },

  pricing: {
    kicker: 'Pricing',
    title: 'Simple, transparent pricing for AI dramas',
    subtitle: 'All prices in USD. Cancel anytime. First episode of every AI drama is always free.',

    vipKicker: 'VIP Membership',
    vipTitle: 'Unlimited AI Drama Access',
    vipSubtitle: 'Subscribe to Star Marastel VIP and enjoy unlimited access to our entire AI drama library — no ads, no waiting.',
    mostPopular: 'Most Popular',
    choosePlan: 'Choose Plan',

    vipPlans: [
      { name: 'Monthly', price: '9.99', period: '/mo', description: 'Flexible monthly billing. Cancel anytime. Perfect for first-time AI drama viewers.', features: ['Full AI drama library, no limits', 'HD quality (1080p)', 'Multi-device sync', 'No ads, no popups', 'Cancel anytime'] },
      { name: 'Quarterly', price: '24.99', period: '/3 mo', description: 'Best for binge-watchers. Save 17% vs monthly.', features: ['Everything in Monthly', '4K Ultra HD quality', 'Save 17% vs monthly', 'Priority support', 'Early access to new AI dramas'], popular: true },
      { name: 'Annual', price: '79.99', period: '/yr', description: 'Maximum savings for loyal fans — up to 33% off.', features: ['Everything in Quarterly', 'Save 33% vs monthly', 'Exclusive VIP-only AI content', 'Offline download', 'Dedicated support'] }
    ],

    creditKicker: 'Credit Packs',
    creditTitle: 'Pay per episode, credits never expire',
    creditSubtitle: 'Buy credits to unlock single episodes. 1 credit = 1 episode. Great for sampling before you commit.',
    creditLabel: 'Credits',
    creditRate: '~$0.10 / episode',
    buyCreditPack: 'Buy Credit Pack',

    creditPacks: [
      { credits: '50', price: '4.99', features: ['50 AI drama episode unlocks', 'Credits never expire', 'Starter pack'] },
      { credits: '200', price: '19.99', features: ['200 AI drama episode unlocks', 'Credits never expire', 'Most popular'] },
      { credits: '500', price: '49.99', features: ['500 AI drama episode unlocks', 'Credits never expire', 'Best value'] }
    ],

    faqKicker: 'FAQ',
    faqTitle: 'You might be wondering',
    faqs: [
      { q: 'What payment methods are supported?', a: 'We accept all major credit/debit cards (Visa, Mastercard, American Express), plus Apple Pay and Google Pay. All payments are securely encrypted by Stripe.' },
      { q: 'Can I cancel my membership anytime?', a: 'Yes. You can cancel VIP membership anytime from your account or by contacting support. Access continues until the end of the current billing period; renewal stops automatically.' },
      { q: 'Do credits expire?', a: 'No. Purchased credits are permanent. Unlock any episode, anytime — no time pressure.' },
      { q: 'Is the first episode really free?', a: 'Yes. The first episode of every AI drama on Star Marastel is completely free. No account needed, no payment required. Just click and watch.' },
      { q: 'What currency are prices in?', a: 'All prices and settlements on the platform are in US dollars (USD). If your card uses another currency, your bank will convert at the day\'s exchange rate.' },
      { q: 'What\'s the refund policy?', a: 'Since digital content cannot be returned once accessed, consumed credits and watched episodes are non-refundable. Subscription fees can be refunded within 7 days of purchase. See our Refund Policy for details.' }
    ],

    ctaTitle: 'Still have questions?',
    ctaSubtitle: 'Our team is ready to help you choose the best AI drama plan.',

    modalVip: 'VIP Membership',
    modalCredit: 'Credit Pack',
    modalDefaultDesc: 'Flexible pay-per-use. Credits never expire.',
    modalContact: 'Contact Support to Purchase',
    modalKeepBrowsing: 'Keep Browsing',
    modalCreditPack: (n) => `${n} Credit Pack`
  },

  contact: {
    kicker: 'Contact Us',
    title: 'Get in touch',
    subtitle: 'Questions about plans, payments, or content? We\'re online 24/7 and ready to help.',

    directTitle: 'Reach us directly',
    emailLabel: 'Email',
    phoneLabel: 'Support Phone',
    addressLabel: 'Office Address',
    hoursLabel: 'Hours',
    hoursDetail: 'Support Center: 24/7\nBilling Dept: Mon–Fri 9:00–18:00 (GMT+8)',

    formTitle: 'Send a message',
    nameLabel: 'Name',
    namePlaceholder: 'Your name',
    emailField: 'Email',
    emailPlaceholder: 'you@marastel.com',
    subjectLabel: 'Subject',
    subjectPlaceholder: 'How can we help?',
    messageLabel: 'Message',
    messagePlaceholder: 'Please describe your question or feedback in detail...',
    sendButton: 'Send Message',
    sending: 'Sending...',

    errorDefault: 'Failed to send. Please try again later.',
    errorNetwork: 'Network error. Please check your connection and retry.',

    successTitle: 'Message sent successfully!',
    resend: 'Send another'
  },

  router: {
    home: 'Home',
    pricing: 'Pricing',
    vip: 'VIP Membership',
    credits: 'Credits',
    contact: 'Contact',
    privacy: 'Privacy Policy',
    refund: 'Refund Policy',
    terms: 'Terms of Service'
  },

  vipPage: {
    kicker: 'VIP Center',
    title: 'Star Marastel VIP',
    subtitle: 'Subscribe to VIP and unlock unlimited access to our entire AI drama library.',

    statusActive: 'VIP Member',
    statusExpired: 'Not a Member',
    daysLeft: (n) => `${n} days remaining`,
    levelSource: 'Activated via Monthly plan',
    levelNormal: 'Standard',
    levelSilver: 'Silver',
    levelGold: 'Gold',
    levelPlatinum: 'Platinum',
    days: (n) => `${n} days`,

    benefitTitle: 'VIP Member Benefits',
    benefitSubtitle: 'Exclusive perks at every level',
    benefitHeaders: ['Feature', 'Free', 'Monthly', 'Quarterly', 'Annual'],
    benefits: [
      { name: 'Full AI drama library', free: false, monthly: true, quarterly: true, yearly: true },
      { name: 'Daily new AI series', free: true, monthly: true, quarterly: true, yearly: true },
      { name: 'No ads, no popups', free: false, monthly: true, quarterly: true, yearly: true },
      { name: 'HD quality (1080p)', free: false, monthly: true, quarterly: true, yearly: true },
      { name: '4K Ultra HD', free: false, monthly: false, quarterly: true, yearly: true },
      { name: 'Early access to new AI dramas', free: false, monthly: false, quarterly: true, yearly: true },
      { name: 'Offline downloads', free: false, monthly: false, quarterly: false, yearly: true },
      { name: 'VIP-exclusive AI content', free: false, monthly: false, quarterly: false, yearly: true }
    ],
    benefitYes: '✓',
    benefitNo: '—',

    planSectionKicker: 'Choose a Plan',
    planSectionTitle: 'Upgrade to VIP Today',
    planSectionSubtitle: 'Flexible monthly billing, cancel anytime. Save more with Quarterly or Annual.',
    renewBtn: 'Renew',
    subscribeBtn: 'Get VIP',

    historyTitle: 'Purchase History',
    historyEmpty: 'No purchase records',
    historyColumns: ['Plan', 'Purchased', 'Valid Period', 'Status', 'Amount'],
    historyStatusActive: 'Active',
    historyStatusExpired: 'Expired',

    historyData: [
      { name: 'Quarterly Plan', purchasedAt: '2026-08-15', validFrom: '2026-08-15', validTo: '2026-11-14', status: 'active', price: '$24.99' },
      { name: 'Monthly Plan', purchasedAt: '2026-06-01', validFrom: '2026-06-01', validTo: '2026-06-30', status: 'expired', price: '$9.99' },
      { name: 'Annual Plan', purchasedAt: '2026-01-10', validFrom: '2026-01-10', validTo: '2027-01-09', status: 'expired', price: '$79.99' }
    ],

    ctaTitle: 'Still have questions?',
    ctaSubtitle: 'Our team is ready to help you with anything about VIP membership.'
  },

  creditsPage: {
    kicker: 'Credits',
    title: 'Credits — Unlock episode by episode',
    subtitle: 'Buy credit packs to unlock single AI drama episodes. Credits never expire. Unlock anytime, anywhere.',

    balanceLabel: 'My Credits',
    balanceHint: '1 credit = 1 AI drama episode unlocked',
    purchaseBtn: 'Recharge',

    rechargeTitle: 'Pick a Credit Pack',
    rechargeSubtitle: 'Perfect for sampling before you binge. Great value guaranteed.',
    popularTag: 'Most Popular',
    buyBtn: 'Buy Now',

    rechargePacks: [
      { credits: '50', price: '4.99', originalPrice: '6.00', bonus: null, tag: null, perks: ['50 AI drama episode unlocks', 'Credits never expire', 'Starter pack'] },
      { credits: '200', price: '19.99', originalPrice: '24.00', bonus: '+30', tag: 'Most Popular', perks: ['200 AI drama episode unlocks', '30 bonus credits', 'Credits never expire', '~$0.09 / episode'] },
      { credits: '500', price: '49.99', originalPrice: '60.00', bonus: '+100', tag: 'Best Value', perks: ['500 AI drama episode unlocks', '100 bonus credits', 'Credits never expire', '~$0.08 / episode'] },
      { credits: '1000', price: '99.99', originalPrice: '120.00', bonus: '+250', tag: 'Super Fan', perks: ['1000 AI drama episode unlocks', '250 bonus credits', 'Credits never expire', '~$0.07 / episode'] }
    ],

    howToTitle: 'How do Credits work?',
    howToSubtitle: 'Three simple steps to start watching',
    steps: [
      { title: 'Buy a Credit Pack', desc: 'Choose the pack that fits you. Secure checkout with Stripe.' },
      { title: 'Browse AI Dramas', desc: 'The first episode is always free — preview before you commit.' },
      { title: 'Unlock Episodes You Love', desc: 'Click "Unlock" — 1 credit = 1 episode. Simple as that.' }
    ],

    historyTitle: 'Credit History',
    historyEmpty: 'No credit activity',
    historyColumns: ['Type', 'Description', 'Time', 'Change'],
    typePurchase: 'Purchase',
    typeUnlock: 'Unlock',
    typeBonus: 'Bonus',
    typeRefund: 'Refund',

    historyData: [
      { type: 'purchase', desc: 'Purchased 200 Credit Pack', time: '2026-09-08 14:32', delta: 230 },
      { type: 'unlock', desc: 'Unlocked "Hidden Love" Ep. 24', time: '2026-09-08 15:10', delta: -1 },
      { type: 'unlock', desc: 'Unlocked "Midnight Contract" Ep. 8', time: '2026-09-07 21:05', delta: -1 },
      { type: 'unlock', desc: 'Unlocked "City Lights" Ep. 15', time: '2026-09-07 12:48', delta: -1 },
      { type: 'bonus', desc: 'Quarterly VIP Bonus Credits', time: '2026-08-15 09:00', delta: 50 },
      { type: 'purchase', desc: 'Purchased 50 Credit Pack', time: '2026-08-10 16:20', delta: 50 }
    ],

    plus: (n) => `+${n}`,
    minus: (n) => `-${n}`,
    today: 'Today',
    yesterday: 'Yesterday',

    ctaTitle: 'Questions about Credits?',
    ctaSubtitle: 'Reach out to our support team anytime.'
  },

  lang: {
    switchToEn: 'English',
    switchToZh: '中文',
    label: 'Language'
  },

  company: {
    name: 'Star Marastel Co., Limited',
    address: 'RM 1503-09, 15/F, Causeway Bay Centre, 15-23 Sugar St, Causeway Bay, Hong Kong',
    email: 'trendameasor@mail.com',
    phone: '+852 6123 4567'
  }
}
